# Specify audits to run. Also include any plugins (like axe)
audits:
    - axe
    - lighthouse
    - heap-snapshot
    - source-map-explorer

configs:
    logger:
        level: 1
    comment:
        # Only show failures in GitHub PR comments.
        # Useful to pinpoint why a build has failed
        onlyFailures: false
    buildDir: public
    # Heap snapshot settings
    heap-snapshot:
        threshold:
            Documents: 11
            Frames: 5
            JSHeapTotalSize: 13356000
            JSHeapUsedSize: 10068000
            Nodes: 800
            RecalcStyleCount: 15
            LayoutCount: 15

    # Lighthouse settings
    lighthouse:
        skipAudits:
            - uses-http2
            - redirects-http
            - uses-long-cache-ttl
            - uses-text-compression
        outputHtml: ./gimbal-artifacts/lighthouse.html
        threshold:
            accessibility: 90
            "best-practices": 92
            performance: 64
            pwa: 52
            seo: 85

# Locations of reports. Useful for storing artifacts in CI
outputs:
    # Only show failures in CLI
    cli:
        onlyFailures: false
    markdown: ./gimbal-artifacts/results.md

# Plugins
plugins:
    - plugin: "@modus/gimbal-plugin-last-value"
      saveOnlyOnSuccess: false

    - plugin: "@modus/gimbal-plugin-axe"
      thresholds:
          aria-allowed-attr: critical
          color-contrast: serious
          landmark-one-main: moderate
          landmark-complementary-is-top-level: moderate
          meta-viewport: critical
          region: moderate
          page-has-heading-one: moderate
          scrollable-region-focusable: moderate

    - plugin: "@modus/gimbal-plugin-sqlite"
      enabled: true
      commandPrefix:
          - wamburu-blog
      lastValue: true
