name: CI

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '10.13'
      - name: Install npm dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Performance Budgeting Regression Testing
        uses: ModusCreateOrg/gimbal/action@master
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GIMBAL_KEY }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: Upload to artifacts
          path: gimbal-artifacts/

      - name: Add results to comment
        uses: harupy/comment-on-pr@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ./gimbal-artifacts/results.md
